# Generated by Django 5.2 on 2025-04-21 08:06

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='interesting/thumbs/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='interesting/music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])], verbose_name='Аудио файл')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность')),
                ('artist', models.CharField(blank=True, max_length=255, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Музыка',
                'verbose_name_plural': 'Музыка',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='interesting/thumbs/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='interesting/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='Видео файл')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание мероприятия')),
                ('short_description', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('program', models.TextField(blank=True, help_text='Детальное описание программы мероприятия. Можно использовать HTML-разметку', null=True, verbose_name='Программа мероприятия')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('current', 'Предстоящее'), ('past', 'Прошедшее')], max_length=10, verbose_name='Статус мероприятия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status'], name='astana_fund_status_fcb232_idx'), models.Index(fields=['start_date', 'end_date'], name='astana_fund_start_d_234380_idx'), models.Index(fields=['is_active'], name='astana_fund_is_acti_223d90_idx')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='interesting/thumbs/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('content', models.TextField(verbose_name='Содержание статьи')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='Время чтения (мин)')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='astana_fund.interestingtag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='MediaPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок публикации')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-адрес')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор')),
                ('source', models.CharField(max_length=255, verbose_name='Источник (СМИ)')),
                ('source_url', models.URLField(blank=True, verbose_name='Ссылка на оригинал')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('full_content', models.TextField(blank=True, verbose_name='Полный текст')),
                ('publication_type', models.CharField(choices=[('article', 'Статья'), ('interview', 'Интервью'), ('report', 'Репортаж'), ('photo', 'Фоторепортаж'), ('video', 'Видеоматериал')], default='article', max_length=20, verbose_name='Тип публикации')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='media_publications/', verbose_name='Главное изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Публикация СМИ',
                'verbose_name_plural': 'Публикации СМИ',
                'ordering': ['-publication_date'],
                'indexes': [models.Index(fields=['publication_type'], name='astana_fund_publica_d10596_idx'), models.Index(fields=['is_published'], name='astana_fund_is_publ_e271f0_idx'), models.Index(fields=['publication_date'], name='astana_fund_publica_656f64_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-адрес')),
                ('short_description', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('status', models.CharField(choices=[('current', 'Текущий проект'), ('completed', 'Завершен'), ('permanent', 'Постоянный')], default='current', max_length=20, verbose_name='Статус проекта')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('location', models.CharField(max_length=255, verbose_name='Место реализации')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Главное изображение')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый проект')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-is_featured', '-start_date'],
                'indexes': [models.Index(fields=['status'], name='astana_fund_status_905cb9_idx'), models.Index(fields=['is_featured'], name='astana_fund_is_feat_6b9604_idx')],
            },
        ),
    ]
