# Generated by Django 5.1.5 on 2025-04-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astana_fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cultures_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество представленных культур'),
        ),
        migrations.AddField(
            model_name='event',
            name='guests_count',
            field=models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='Количество гостей'),
        ),
        migrations.AddField(
            model_name='event',
            name='performances_count',
            field=models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name='Количество выступлений'),
        ),
    ]
