# Generated by Django 5.1.5 on 2025-04-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astana_fund', '0002_event_cultures_count_event_guests_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(max_length=10, verbose_name='Статус мероприятия'),
        ),
    ]
