# Generated by Django 5.1.5 on 2025-04-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astana_fund', '0004_eventimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventimage',
            options={'verbose_name': 'Фотография мероприятия', 'verbose_name_plural': 'Фотографии мероприятия'},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='astana_fund_status_fcb232_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение-постер'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='astana_fund.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to='event_gallery/', verbose_name='Изображение'),
        ),
    ]
